CREATE TABLE users (
                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username varchar(50) NOT NULL UNIQUE,
                       email varchar(255) NOT NULL UNIQUE,
                       password varchar(255) NOT NULL,
                       created_at timestamp not null,
                       updated_at timestamp not null,
                       CONSTRAINT email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    );

CREATE TABLE post (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(100) not null,
                      content TEXT not null,
                      user_id bigint references users(id),
                      created_at timestamp not null,
                      updated_at timestamp not null
);

CREATE TABLE commentary (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            text TEXT not null,
                            user_id bigint references users(id),
                            post_id bigint references post(id),
                            created_at timestamp not null,
                            updated_at timestamp not null
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            roles VARCHAR(255),
                            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_following (
                                follower_id bigint not null,
                                following_id bigint not null,
                                created_at timestamp default current_timestamp,
                                PRIMARY KEY (follower_id, following_id),
                                FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
                                FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE,
                                CONSTRAINT check_self_follow CHECK (follower_id != following_id)
);